"""
Version information for the UoM Deep Learning Workshop utilities package.
Auto-generated by GitHub Actions CI/CD pipeline.
"""

# Version information
__version__ = ""
__commit__ = "032bb7f"
__version_full__ = "+032bb7f"
