"""
Version information for the UoM Deep Learning Workshop utilities package.
Auto-generated by GitHub Actions CI/CD pipeline.
"""

# Version information
__version__ = ""
__commit__ = "0b5fac6"
__version_full__ = "+0b5fac6"
